repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        args: [-S]
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.4.0
    hooks:
      - id: pip-compile
        args: [--generate-hashes, --allow-unsafe]
        files: ^requirements\.in$
      - id: pip-compile
        name: pip-compile dev
        args: [requirements-dev.in, --generate-hashes, --allow-unsafe, -o requirements-dev.txt]
        files: ^requirements-dev\.in$
